"""add missing columns to backtest tables

Revision ID: 7205bc02b030
Revises: a5bd6e50f51e
Create Date: 2026-02-13 19:29:35.791883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7205bc02b030'
down_revision: Union[str, Sequence[str], None] = 'a5bd6e50f51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_run', sa.Column('asset_id', sa.String(length=20), nullable=False))
    op.add_column('backtest_run', sa.Column('metrics_json', sa.JSON(), nullable=True))
    op.add_column('backtest_trade_log', sa.Column('entry_price', sa.Float(), nullable=False))
    op.add_column('backtest_trade_log', sa.Column('exit_price', sa.Float(), nullable=True))
    op.add_column('backtest_trade_log', sa.Column('shares', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_trade_log', 'shares')
    op.drop_column('backtest_trade_log', 'exit_price')
    op.drop_column('backtest_trade_log', 'entry_price')
    op.drop_column('backtest_run', 'metrics_json')
    op.drop_column('backtest_run', 'asset_id')
    # ### end Alembic commands ###
