"""initial: 8 tables

Revision ID: a5bd6e50f51e
Revises:
Create Date: 2026-02-10 23:32:32.166955

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a5bd6e50f51e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_master',
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('source_priority', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('backtest_equity_curve',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'date')
    )
    op.create_table('backtest_run',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('backtest_trade_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factor_daily',
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('factor_name', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id', 'date', 'factor_name', 'version')
    )
    op.create_index(
        'ix_factor_daily_asset_date', 'factor_daily',
        ['asset_id', sa.literal_column('date DESC')], unique=False,
    )
    op.create_table('job_run',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('price_daily',
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column(
        'ingested_at', sa.DateTime(timezone=True),
        server_default=sa.text('now()'), nullable=False,
    ),
    sa.PrimaryKeyConstraint('asset_id', 'date', 'source')
    )
    op.create_index(
        'ix_price_daily_asset_date', 'price_daily',
        ['asset_id', sa.literal_column('date DESC')], unique=False,
    )
    op.create_index('ix_price_daily_date', 'price_daily', ['date'], unique=False)
    op.create_table('signal_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('strategy_id', sa.String(length=50), nullable=False),
    sa.Column('signal', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_signal_daily_asset_date_strategy', 'signal_daily',
        ['asset_id', 'date', 'strategy_id'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signal_daily_asset_date_strategy', table_name='signal_daily')
    op.drop_table('signal_daily')
    op.drop_index('ix_price_daily_date', table_name='price_daily')
    op.drop_index('ix_price_daily_asset_date', table_name='price_daily')
    op.drop_table('price_daily')
    op.drop_table('job_run')
    op.drop_index('ix_factor_daily_asset_date', table_name='factor_daily')
    op.drop_table('factor_daily')
    op.drop_table('backtest_trade_log')
    op.drop_table('backtest_run')
    op.drop_table('backtest_equity_curve')
    op.drop_table('asset_master')
    # ### end Alembic commands ###
